import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Projects.module.scss'

import ProjectList  from '../components/ProjectList'


const inter = Inter({ subsets: ['latin'] })

import { supabase } from './../lib/supabaseClient';
export async function getServerSideProps(context:any) {

    const { data } = await supabase.from('project')
        .select()
        .eq('active', true);
        
    console.log(data);

    return {
        props: {
        projects: data
        }, // will be passed to the page component as props
    }
}
  

export default function Projects({projects}: any) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>        
        <ProjectList projects={projects}/>
      </main>
    </>
  )
}
